#pragma once

namespace numerical {namespace utils {
	#define WARNING_ENUMERATE_HAS_NO_HANDLER 4061
	#define WARNING_UNREFERENCED_FORMAL_PARAMETER 4100
	#define WARNING_CONDITIONAL_EXPRESSION_IS_CONSTANT 4127
	#define WARNING_UNSAFE_CONVERSION 4191
	#define WARNING_NAMELESS_STRUCT_OR_UNION 4201
	#define WARNING_CAST_ON_LEFT_VALUE 4213
	#define WARNING_EXCEPTION_SPECIFICATION_IGNORED 4290
	#define WARNING_STRUCTURE_WAS_PADDED 4324
	#define WARNING_USING_OF_UNDEFINED_TYPE_IN_CLR 4339
	#define WARNING_BEHAVIOR_CHANGE 4350
	#define WARNING_NEW_BEHAVIOR_ELEMENTS_OF_ARRAY_WILL_BE_DEFAULT_INITIALIZED 4351
	#define WARNING_THIS_USED_FOR_INITIALIZATION_LIST 4355
	#define WARNING_CONVERSION_SIGNED_UNSIGNED_MISMATCH 4365
	#define WARNING_ENUMERATION_MUST_HAVE_AN_UNDERLYING_TYPE 4471
	#define WARNING_ENUMERATION_IS_MACHINE 4472
	#define WARNING_UNREFERENCED_LOCAL_FUNCTION_HAS_BEEN_REMOVED 4505
	#define WARNING_UNREFERENCED_INLINE_FUNCTION_HAS_BEEN_REMOVED 4514
	#define WARNING_MULTIPLE_ASSIGNMENT_OPERATORS_SPECIFIED 4522
	#define WARNING_DIGRAPHS_NOT_SUPPORTED 4628
	/* [Deprecated("Local static object is thread safe in future compiler releases")] */
	#define WARNING_LOCAL_STATIC_OBJECT_IS_NOT_THREAD_SAFE 4640
	#define WARNING_FUNCTION_NOT_INLINED 4710
	#define WARNING_FUNCTION_SELECTED_FOR_INLINE_EXPANSION 4711
	#define WARNING_FLOAT_POSSIBLE_LOSS_OF_PERFORMANCE 4738
	#define WARNING_BYTES_PADDING_ADDED 4820
	#define WARNING_GUID_ASSOCIATION 4917
	#define WARNING_NONSTANDARD_EXTENSION_USED 4987
	#define WARNING_FUNCTION_WAS_DECLARED_DEPRECATED 4996
	#define WARNING_MOVE_CONSTRUCTOR_WAS_IMPLICITLY_DEFINED_AS_DELETED 5024
	#define WARNING_MOVE_ASSIGNMENT_OPERATOR_WAS_IMPLICITLY_DEFINED_AS_DELETED 5025
}}